### PR TITLE
[SCH-294] Add tracking plan support to page()

### PR DESCRIPTION
**Pull request by Rowno**
https://segment.atlassian.net/browse/SCH-294

@segmentio/schema

### CODE REVIEW

**Comment by f2prateek** [comment]
This is going to break some integrations - some integrations require `page` to be called (instead of intialize, they are iniialized on a page call). See this doc for reference https://paper.dropbox.com/doc/Research-AssumesPageview-Fix-dpTYzw1pW9infEElyWNvS.

**Comment by Rowno** [comment]
Nope, and I don't understand how this breaks them.

**Comment by danielstjules** [comment]
@f2prateek can you clarify how you think it would impact those integrations?

https://github.com/segmentio/analytics.js-integration/blob/e8cc1b0c2264fbc44f0b5ae72efb003e47535007/README.md#assumespageview

> Mark the Integration as assuming an initial pageview has happened when its Javascript library loads. This is important for integrations whose libraries assume a "pageview" in their interface as soon as the library loads, instead of exposing a .page() method or similar to call via Javascript.
> This option changes the integration so that the very first call to page actually initializes the integration, ensuring that the pageviews aren't accidentally duplicated.

Based on the above, it sounds like this wouldn't break integrations that automatically fire pageview on initialization, but instead, our tracking plan and schema wouldn't apply to the first call of those integrations. Is that correct?

**Comment by f2prateek** [comment]
> This option changes the integration so that the very first call to page actually initializes the integration, ensuring that the pageviews aren't accidentally duplicated.

Key part is this: `very first call to page actually initializes the integration`. So now with this change, we won't call page on integrations. This will lead to two problems:

1. "Deadlock" issue for customers that are using `analytics.ready()`  since those integrations would never be "ready". (similar to what described in https://paper.dropbox.com/doc/Research-AssumesPageview-Fix-dpTYzw1pW9infEElyWNvS#:uid=687300514527754&h2=What-is-assumesPageview).
2. That integration won't process any subsequent events (track/identify/etc.), since it'll never be initialized and never be "ready" to receive events.

**Comment by f2prateek** [comment]
Hey folks, you can actually disregard https://github.com/segmentio/analytics.js-core/pull/60#issuecomment-368087235; turns out it this used to be an issue but has been fixed for a while (https://github.com/segmentio/analytics.js-integration/commit/7597a6fa0127d1cf3c670e36453866d628814df7). There's still a discussion to be had around making changes so close to a.js core without a canary testing system in place, but otherwise this should work as expected!

**Pull request closed without merging**
