### PR TITLE
docs(readme): fix typo in ajs snippet section

### PR DESCRIPTION
**Pull request by dankreiger**
## Description

This Fixes a small typo in `README.md`. 

- New version is not required.
- Testing not required.

## Test plan

N/A 

## Release plan

N/A

## Checklist

N/A

### CODE REVIEW

**Comment by bryanmikaelian** [comment]
Thanks for this!

**Comment by bryanmikaelian** [comment]
Just an update @dankreiger.  We're going to get this merged this week!

**Comment by juliofarah** [comment]
Hey @dankreiger I'm so sorry we took so long to get back to this.

Would you be so kind to rebase this PR with the latest version of master?
I'll merge it right away after that.

**Comment by juliofarah** [comment]
@dankreiger thanks again for contributing to analytics.js
I'm fixing this issue on our side and closing this PR.

**Pull request closed without merging**
